[package]
name = "lazy-pool"
version = "0.1.1"
authors = ["Giorgos Georgiou <giorgos.georgiou@outlook.com>"]
description = "Experimental lazy object pool"
repository = "https://github.com/behos/lazy-pool"
license = "Apache-2.0"

[dependencies]
futures = "~0.1"

[dev-dependencies]
uuid = { version = "~0", features = ["v4"] }
